version: "3"

services:
  picodesign:
    container_name: picodesign
    image: nginx
    volumes:
      - './:/usr/share/nginx/html'
    restart: unless-stopped
networks:
  default:
    external:
      name: nginx